### ISSUE TITLE
Livereload issue with eventmachine gem

### ISSUE THREAD

**Issue by steveoh** [RobertDeRose/jekyll-livereload#11]
I'm having an issue getting up and going with live reload. It's having an issue with `eventmachine`. I tried adding it to my gemfile but that doesn't seem to make a difference. Can you tell what I am missing?

### Gemfile
```ruby
source 'https://rubygems.org'
group :plugins do
    gem 'jekyll'
    gem 'liquid_reading_time'
    gem 'liquid_pluralize'
    gem 'eventmachine'
    gem 'jekyll-livereload'
end
```

### _config.yml
```yml
livereload: true
reload_port: 35729
```

### docker-compose.yml
```yaml
version: "2"

services:
  jekyll:
    container_name: "gis.utah.gov"
    image: "jekyll/jekyll:pages"
    command: "jekyll serve --watch --incremental"
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "127.0.0.1:4000:4000"
```

### Terminal

```gis.utah.gov | An error occurred while installing eventmachine (1.2.5), and Bundler cannot
gis.utah.gov | continue.
gis.utah.gov | Make sure that `gem install eventmachine -v '1.2.5'` succeeds before bundling.
gis.utah.gov |
gis.utah.gov | In Gemfile:
gis.utah.gov |   jekyll-livereload was resolved to 0.2.2, which depends on
gis.utah.gov |     em-websocket was resolved to 0.5.1, which depends on
gis.utah.gov |       eventmachine
```

It looks like the `jekyll/jekyll:pages` image doesn't work with this plugin but it does seem to work with the `jekyll/jekyll` image.

Even then though I can't get livereload to register as a cli option.
